In [13]:
import cv2
import numpy as np
# Load video stream
cap = cv2.VideoCapture('F:/Master OpenCV/images/walking.avi')

# Get first frame
ret, first_frame = cap.read()
previous_gray = cv2.cvtColor(first_frame, cv2.COLOR_BGR2GRAY)
hsv = np.zeros_like(first_frame)
hsv[...,1]=255
while True:

    # Read of video file
    ret, frame2 = cap.read()
    next = cv2.cvtColor(frame2,cv2.COLOR_BGR2GRAY)

    # Computes the dense optical flow using the Gunnar Farneback’s algorithm
    flow = cv2.calcOpticalFlowFarneback(previous_gray, next,
                                        None, 0.5, 3, 15, 3, 5, 1.2, 0)

    # use flow to calculate the magnitude (speed) and angle of motion
    # use these values to calculate the color to reflect speed and angle
    magnitude, angle = cv2.cartToPolar(flow[...,0], flow[...,1])
    hsv[...,0] = angle * (180 / (np.pi/2))
    hsv[...,2] = cv2.normalize(magnitude, None, 0, 255, cv2.NORM_MINMAX)
    final = cv2.cvtColor(hsv, cv2.COLOR_HSV2BGR)

    # Show our demo of Dense Optical Flow
    cv2.imshow('Dense Optical Flow', final)
    if cv2.waitKey(1) == 13: #13 is the Enter Key
        break

    # Store current image as previous image
    previous_gray = next

cap.release()
cv2.destroyAllWindows()

In [14]:
flow = cv2.calcOpticalFlowFarneback(previous_gray, next,
                                        None, 0.5, 3, 15, 3, 5, 1.2, 0)

In [16]:
flow.shape

(576, 768, 2)

In [17]:
magnitude, angle = cv2.cartToPolar(flow[...,0], flow[...,1])
magnitude

array([[0.03144786, 0.05192957, 0.07390801, ..., 0.04512309, 0.04549347,
        0.06265982],
       [0.03645226, 0.05823913, 0.08096094, ..., 0.04567246, 0.04224479,
        0.05343219],
       [0.04255676, 0.06625067, 0.09034068, ..., 0.0471663 , 0.04152283,
        0.04528845],
       ...,
       [0.00696694, 0.00715365, 0.00774951, ..., 0.01993479, 0.02265073,
        0.02705526],
       [0.00305275, 0.00325317, 0.003956  , ..., 0.00901742, 0.01079803,
        0.01150576],
       [0.00029146, 0.00020422, 0.00026516, ..., 0.00457164, 0.00460252,
        0.00454536]], dtype=float32)

In [18]:
angle



array([[1.3339832, 1.4276316, 1.5002974, ..., 4.0099993, 3.5228856,
        3.0307403],
       [1.3123217, 1.396997 , 1.470759 , ..., 4.1644983, 3.7424517,
        3.1761456],
       [1.3457862, 1.4142063, 1.4786273, ..., 4.308374 , 3.9903846,
        3.3706014],
       ...,
       [4.217986 , 4.2633243, 4.3750763, ..., 5.0246596, 4.6505113,
        4.409506 ],
       [4.4682827, 4.44218  , 4.558355 , ..., 3.7300277, 3.5796626,
        3.4800196],
       [5.8996625, 5.6962166, 4.701893 , ..., 3.7034853, 3.489412 ,
        3.2829745]], dtype=float32)

In [19]:
(angle*360)/np.pi

array([[152.8632 , 163.59453, 171.92142, ..., 459.51205, 403.69293,
        347.29724],
       [150.38098, 160.08406, 168.53658, ..., 477.21634, 428.85336,
        363.95944],
       [154.21573, 162.05609, 169.4382 , ..., 493.70328, 457.26437,
        386.24246],
       ...,
       [483.34558, 488.54095, 501.3468 , ..., 575.78357, 532.9093 ,
        505.29214],
       [512.02747, 509.03632, 522.34894, ..., 427.42966, 410.1991 ,
        398.78085],
       [676.05145, 652.7383 , 538.7972 , ..., 424.38812, 399.85715,
        376.20117]], dtype=float32)